### ISSUE TITLE
Lines 97-98

### ISSUE THREAD

**Issue by jdrakephd** [CEIDatUGA/COVID-stochastic-fitting#1]
I don't understand lines 97-98 on make-pomp-model. Possible error. Line 98 says it is for three transitions, but only two rates are passed. The transitions from line 97 should possibly be on this line

**Comment by jdrakephd** [comment]
Related, are we confident we have the syntax right for reulermultinom? It doesn't match documentation, eg. here: https://kingaa.github.io/pomp/vignettes/C_API.html#multinomial-distribution

**Comment by atredennick** [comment]
Hmm. This looks correct to me.

`reulermultinom(3, E4, &rate[3], dt, &trans[5]); ` says there are 3 potential "movements" that come out of the E4 number of individuals following rates `rate[3]`, `rate[4]`, and `rate[5]`, `dt` is just for time interval, and we assign the number of transitions to `trans[5]`, `trans[6]`, and `trans[7]`. Those `trans` are then used to balance the equations starting on line 133.

The `&` symbol in C code creates automatic pointers to that iterate through `rate` and `trans` starting at the value in the index (`i`) to `i+(3-1)`.

This also follows the documentation, as I read it. It also matches pomp examples and other code that Eamon and I have written. Following the documentation

`reulermultinom(3, E4, &rate[3], dt, &trans[5]); `

- m = `3`, a positive integer, is number of potential transitions ("transitions" to Ia, Isu, Isd)
- size = `E4`, a positive integer, is the number of individuals at risk (pop size in E4).
- rate is a pointer to the vector of transition (“death”) rates (here `rate[3:5]` but in C form with the `&`).
- dt, a positive real number, is the duration of time interval.
- trans is a pointer to the vector that will hold the random deviate (here `trans[5:7]` but in C form with the `&`).

Perhaps I am missing someting? We could have @e3bo confirm/double check.

**Comment by jdrakephd** [comment]
Okay - I think I get it now - thanks
