### ISSUE TITLE
Jobs failing

### ISSUE THREAD

**Issue by allopole** [CEIDatUGA/COVID-stochastic-fitting#11]
Jobs failing. The function `loadcleandata()` has a new argument `trim = TRUE` that trims off the beginning of each state's dataset to the date of the first reported case or death. Relevant code here: [loadcleandata.R](https://github.com/CEIDatUGA/COVID-stochastic-fitting/blob/master/code/data-processing/loadcleandata.R#L189-205). The idea is that the model may have trouble fitting data with lots of leading zeros.  The function works correctly.

The error happens on line 200 of [code/00-RUN-CLUSTER-ARRAY.R](https://github.com/CEIDatUGA/COVID-stochastic-fitting/blob/master/code/00-RUN-CLUSTER-ARRAY.R#L200-205) when `summarize_simulations()` is called (function code here: [code/forward-simulations/summarize_simulations.R](https://github.com/CEIDatUGA/COVID-stochastic-fitting/blob/master/code/forward-simulations/summarize_simulations.R).) 

Error log: 

```
> # Summarize results
> res_summary <- summarize_simulations(sims_out = pomp_res$scenarios, 
+                                      pomp_data = pomp_res$pomp_data,
+                                      pomp_covar = pomp_res$pomp_covar, 
+                                      location = pomp_res$location,
+                                      mle_sim = pomp_res$sims)
`summarise()` regrouping output by 'SimType', 'Period', 'Date' (override with `.groups` argument)
`summarise()` regrouping output by 'SimType', 'Period', 'Date' (override with `.groups` argument)
Error: Problem with `mutate()` input `N`.
x Input `N` can't be recycled to size 253800.
i Input `N` is `pop_size`.
i Input `N` must be size 253800 or 1, not 3.
Backtrace:
     x
  1. \-global::summarize_simulations(...)
  2.   \-`%>%`(...)
  3.     +-base::withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
  4.     \-base::eval(quote(`_fseq`(`_lhs`)), env, env)
  5.       \-base::eval(quote(`_fseq`(`_lhs`)), env, env)
  6.         \-`_fseq`(`_lhs`)
  7.           \-magrittr::freduce(value, `_function_list`)
  8.             \-function_list[[i]](value)
  9.               +-dplyr::mutate(., N = pop_size)
 10.               \-dplyr:::mutate.data.frame(., N = pop_size)
 11.                 \-dplyr:::mutate_cols(.data, ...)
 12.                   \-base::tryCatch(...)
 13.                     \-base:::tryCatchList(expr, classes, parentenv, handlers)
 14.                       \-base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])
 15.                         \-value[[3L]](cond)
 16.
In addition: Warning messages:
1: attributes are not identical across measure variables;
they will be dropped 
2: attributes are not identical across measure variables;
they will be dropped 
Execution halted
```

**Comment by grighi** [comment]
I haven't built the project and run in debug yet, so not sure what these objects look like. But it looks like this pop_size should be a scalar and in one case it's giving a vector of length 3

'''
pop_size <- sims %>%
    filter(Date == min(Date)) %>%
    pull(S) %>%
    unique()
'''

Could there be some sims where S < pop_size already in period 1? i.e. sims that have their first cases very early. Changing unique() to max() might solve it

**Comment by atredennick** [comment]
I think @grighi's solution should work. So it would be:

```
pop_size <- sims %>%
filter(Date == min(Date)) %>%
pull(S) %>%
max()
```

**Comment by grighi** [comment]
simulations ran successfully after that fix
