### ISSUE TITLE
Warm start 00-RUN-LOCAL.R generating runs with NaN LogLik

### ISSUE THREAD

**Issue by allopole** [CEIDatUGA/COVID-stochastic-fitting#9]
Warm start 00-RUN-LOCAL.R generating runs with NaN LogLik in `pomp_res$all_partable`

This is causing `pomp_res$scenarios <- runscenarios(pomp_res, par_var_list = pomp_res$par_var_list)` (line 242) to fail.

**Comment by atredennick** [comment]
This is fine and just a symptom of not being able to run the MIF algorithm long enough for test runs.
